/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CategorieDAO;
import dao.Connection;
import dao.ProductDAO;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import models.Categorie;
import models.Product;
import view.categorie.CategorieTable;
import view.product.ListTable;

/**
 *
 * @author João Salomão
 */
public class MainFrame extends javax.swing.JFrame {
    // Components
    Component tableProducts;
    Component editCategorie;
    Component categories;
    // Items
    ArrayList<Categorie> categoriesList;
    ArrayList<Product> productsList;
    
    
    /**
     * Creates new form Teste
     */
    public MainFrame() {        
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            Connection.getConnection();
                        
            // Get data from database
            categoriesList = CategorieDAO.index();
            productsList = ProductDAO.index();
            
            // Add  components
            this.jTabbedPane1.add(new ListTable(productsList));
            this.jTabbedPane1.add(new CategorieTable(categoriesList));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "Erro" ,ERROR_MESSAGE);
            System.exit(e.getErrorCode());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Erro" ,ERROR_MESSAGE);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD POO II");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
